### PR TITLE
MySQL Table with constraints.

### PR DESCRIPTION
**Pull request by Nitesh-thapliyal**

### CODE REVIEW

**Comment by amoghrajesh** [comment]
Hey @Nitesh-thapliyal 
Can you add some learner tasks without answers?
For eg: You can in Activity 5, tell them to make the table first and later provide the query. 
Also if possible, cut down the detailing of the steps. It is too detailed (seems like a tutorial)

**Review by amoghrajesh — CHANGES_REQUESTED** [review]
Hey @Nitesh-thapliyal
Can you add some learner tasks without answers?
For eg: You can in Activity 5, tell them to make the table first and later provide the query.
Also if possible, cut down the detailing of the steps. It is too detailed (seems like a tutorial)

**Review by amoghrajesh — APPROVED** [review]
Good work @Nitesh-thapliyal. You did better than I requested you to :)

**Review by sudhanshutiwari264 — APPROVED** [review]
@Nitesh-thapliyal  Nicely done!

**Review by YourAKShaw — APPROVED** [review]
@Nitesh-thapliyal awesome work! :rocket:

**Comment by sudhanshutiwari264** [comment]
Nicely done @Nitesh-thapliyal . Liked ur structure and also good to see you are following the motto of crio.
Next thing that you should do is showcase this PR on microbyte-showcase channel.

Kindly follow the below mentioned format for ur msg @Nitesh-thapliyal  -

All creators who have their PRs accepted and merged can show off their contribution in the microbyte-showcase channel. This will help the other participants by keeping them updated. Also, kindly refrain from spamming the channel with every minor contribution you may make. Please give a brief compiled overview of your contribution.

**Template** (Kindly stick to this format):
Title of your project #(repo-topic)
A brief overview of your project (not more than 3-5 lines). GITHUB LINK of byte must be provided. In the end of this briefing use #(languages), #(software), #(skills) tags.
Actively looking for contributors (both learners and creators). Please raise an issue first and then submit your PRs to that issue only (either after or before assigning the issue to you). Also, you can suggest how they can contribute.

**Template example:**
Concurrency #OS
Brief description. [GITHUB LINK]. #C++ #Python #Shell #Django
Actively looking for contributors. Learners can to this _ and creators can do this __. **Please raise an issue first and then submit your PRs to that issue only.**
#learnbydoing #microbyte-showcase

Needless to say keep contributing!!

**Comment by YourAKShaw** [comment]
@all-contributors kindly add @Nitesh-thapliyal  for code doc ideas content

**Comment by YourAKShaw** [comment]
@all-contributors kindly add @amoghrajesh for review and eventOrganizing

**Comment by Ak-Shaw** [comment]
@all-contributions kindly add @sudhanshutiwari264 for review and eventOrganizing

**Comment by YourAKShaw** [comment]
@all-contributors kindly add @sudhanshutiwari264 for review and eventOrganizing

**Pull request merged**
